name: Go-Build
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - uses: actions/checkout@v3
      - run: go mod download
      - run: go mod download
      - name: Build
        run: go build -v .
