on:
  release:
    types: [created]
name: Build Release
jobs:
  release-linux-amd64:
    name: compile and release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
    - uses: actions/checkout@v3
    - name: compile and release
      uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goarch: ${{ matrix.goos }}
        goos: ${{ matrix.goarch }}
        extra_files: LICENSE README.md
